### ISSUE TITLE
Issue in CMake Error at cmake/modules/ECMAddAppIcon.cmake:113

### ISSUE THREAD

**Issue by AkhmalFirdaus** [nextcloud/client-building#101]
Hi, I'm trying to run the client-building for NC, but got the following error. May I know why and how do I solve it? 
Many thanks.

Input:
```
In Git-Bash:  ../c/Nextcloud/client-building (master)
$ BUILD_INSTALLER=0 USE_CODE_SIGNING=0 UPLOAD_BUILD=0 ./task-build-log.bat
```

Output:
```
..
CMake Error at cmake/modules/ECMAddAppIcon.cmake:113 (message):
  No ICONS argument given to ecm_add_app_icon
Call Stack (most recent call first):
  src/gui/CMakeLists.txt:362 (ecm_add_app_icon)
..
```
...
```
-- Configuring incomplete, errors occurred!
See also "C:/Nextcloud/client-building/desktop/build/CMakeFiles/CMakeOutput.log".
See also "C:/Nextcloud/client-building/desktop/build/CMakeFiles/CMakeError.log".
"*** Build FAILED: desktop Release Win64 (single-build-desktop.bat)"
"***** Build FAILED (build.bat)"
--- END: C:\Nextcloud\client-building\task-build-log.bat - 2021-12-28 09:22:38 ---
```

Full build-log in: https://github.com/AkhmalFirdaus/CMake-Error-when-running-png2ico/blob/main/last-build-2021-12-28-09-18-22-Release.log

All help are highly appreciated.  🙏
Thanks!

**Comment by allexzander** [comment]
@AkhmalFirdaus You are going to need to debug that part of the CMake file src/gui/CMakeLists.txt at line 362. In particular, you need to log what's inside `OWNCLOUD_ICONS_WIN_FOLDER`, and, what's inside the folder that `APP_SECONDARY_ICONS` is pointing to. From your full log I can see that files that must be in the `OWNCLOUD_ICONS_WIN_FOLDER` are correctly generated (see: `Generate 16-Nextcloud-icon-win-folder.png`, `Generate 20-Nextcloud-icon-win-folder.png`, etc. Are they then present in the output folder set to `${APP_SECONDARY_ICONS}/`? There is not much I can do as we don't have this problem.

**Comment by AkhmalFirdaus** [comment]
Alright. Thanks @allexzander for your support. I'll look forward into it.

**Comment by AkhmalFirdaus** [comment]
Hi, @allexzander I got the solution. After a thorough observation as you suggested, it is founded that the ` ICONS ` in my case are not properly assigned.  Somehow, the icon generator is skipped due to `unmatched name calling` (next-for-debug). Hence, the files are not generated in the `OWNCLOUD_ICONS_WIN_FOLDER`.

To overcome this, I directly passed the error by creating an `icon-image.png` as recommended, and hard link it by SET `icon-image.png` PATH to the `<source_var>` in the function lines `ecm_add_app_icon(<source_var> ICONS icon-image.png)` in .../src/gui/CMakeLists.txt 

Save and build.

**Comment by AkhmalFirdaus** [comment]
Hi, @allexzander I got the solution. After a thorough observation as you suggested, it is founded that the ICONS in my case are not properly assigned. Somehow, the icon generator is skipped due to unmatched name calling (next-for-debug). Hence, the files are not generated in the OWNCLOUD_ICONS_WIN_FOLDER.

To overcome this, I directly passed the error by creating an icon-image.png as recommended, and hard link it by SET icon-image.png PATH to the <source_var> in the function lines ecm_add_app_icon(<source_var> ICONS icon-image.png) in .../src/gui/CMakeLists.txt

Save and build.

**Comment by allexzander** [comment]
@AkhmalFirdaus Thx. Feel free to open a PR with a fix if you feel like it makes sense for everyone.
