### ISSUE TITLE
qtkeychain is built without libsecret support in Linux AppImage

### ISSUE THREAD

**Issue by FredericLespez** [nextcloud/client-building#13]
qtkeychain is built without libsecret support.
So on systems using libsecret (Gnome for example), each time the appimage is started, it asked for a password.

I changed the script building the appimage (linux/build-appimage-daily.sh) by installing libsecret-1-dev before qtkeychain is built and upgrading qtkeychain to 0.9.1 (to have a better libsecret support). Now when qtkeychain is build, it autodetect libsecret:
```
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libsecret-1'
--   Found libsecret-1, version 0.18.4
```

And it works : when the appimage is started, it fetches Nextcloud password in Gnome's keyring through libsecret.

I don't know if this building script is also used for the official appimage but it has the same bug. See https://github.com/nextcloud/desktop/issues/427.

**Comment by misch7** [comment]
@FredericLespez Thanks again for your research and work! 🚀 

This is the right place and these are the scripts used on our build servers.

I'm currently upgrading all the build scripts for Linux and macOS, to support Qt 5.12.5 and OpenSSL 1.1.1d, and I'll add this fix to the AppImage build script then soon. Will notify here with a test build to evaluate once it is done.

**Comment by misch7** [comment]
Hey @FredericLespez I've implemented your fix in a test build:
https://download.nextcloud.com/desktop/prereleases/Linux/Nextcloud-2.6.0-Qt-5.12.5-20191016-preview-x86_64.AppImage

Could you give it a try and confirm if it's working with your keyring? :)

**Comment by FredericLespez** [comment]
Hi @misch7,

It works like a charm with my keyring :-)

**Comment by misch7** [comment]
Cool, thanks for testing.

I'll make this a permanent fix then for the build scripts :)
