### ISSUE TITLE
error The system cannot find the file rm.

### ISSUE THREAD

**Issue by bagherfathi** [nextcloud/client-building#14]
when I run build.bat in a command prompt, raise an error: "The system cannot find the file rm."

**Comment by mbnunes** [comment]
U using git bash?

**Comment by brunodemantova** [comment]
I believe that you need to either use git bash, or cmd/powershell with packages that install ubuntu-like functionalities (rm).

**Comment by FlexW** [comment]
Please try to run it from a bash shell.
