### ISSUE TITLE
ocsync.dll signing problme

### ISSUE THREAD

**Issue by ireneuszwojcik** [nextcloud/client-building#17]
I have a problem:
log:
[vcvarsall.bat] Environment initialized for: 'x64'
"** Found signtool.exe: C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\signtool.exe"
"** Code signing begins:"
"*** Sign file: c:/Nextcloud/client-building/collect/Release/Win64/Nextcloud/ocsync.dll."
"* PROJECT_PATH=c:/Nextcloud/client-building"
"* SIGNTOOL=C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\signtool.exe"
"* VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\"
"* APPLICATION_VENDOR=Nextcloud GmbH"
"* P12_KEY=c:/Nextcloud/client-building\key\Nextcloud GmbH.p12"
"* SIGN_FILE_DIGEST_ALG=sha256"
"* SIGN_TIMESTAMP_URL=http://tsa.swisssign.net"
"* SIGN_TIMESTAMP_DIGEST_ALG=sha256"
"* USE_CODE_SIGNING=1"
"* PATH=c:/Nextcloud/tools/cmake/bin;c:/Nextcloud/tools;C:/Program Files (x86)/NSIS;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;c:/Qt/5.12.5/msvc2017_64/bin;c:/Nextcloud/tools/cmake/bin;c:/Nextcloud/tools;C:/Program Files (x86)/NSIS;c:/Nextcloud/tools/cmake/bin;c:/Nextcloud/tools;C:/Program Files (x86)/NSIS;c:/Nextcloud/tools/cmake/bin;c:/Nextcloud/tools;C:/Program Files (x86)/NSIS;C:\Users\cgis\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\cgis\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Users\cgis\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja"
"* Run signtool on file: c:/Nextcloud/client-building/collect/Release/Win64/Nextcloud/ocsync.dll."
Error information: "Error: Store IsDiskFile() failed." (-2147024893/0x80070003)
SignTool Error: An unexpected internal error has occurred.
"*** Sign FAILED for file: c:/Nextcloud/client-building/collect/Release/Win64/Nextcloud/ocsync.dll"
"*** Build FAILED: installer-collect Release Win64 (single-build-installer-collect.bat)"
"***** Build FAILED (build.bat)"
--- END: C:\nextcloud\client-building\task-build-log.bat - 2019-11-03 10:14:35 ---
can you help me?

**Comment by FlexW** [comment]
Please keep in mind that this is not a support forum. You can get help from the community at help.nextcloud.com
