### ISSUE TITLE
Where is the p12 key?

### ISSUE THREAD

**Issue by larslight11** [nextcloud/client-building#18]
Im Missing environment variable: P12_KEY_PASSWORD. But can anyone tell me what this is and how to find it 

``
"*** Build: installer-collect (single-build-installer-collect.bat)"
"* APP_NAME=Nextcloud"
"* APP_NAME_SANITIZED=Nextcloud"
"* USE_BRANDING=0"
"* BUILD_TYPE=Release"
"* BUILD_ARCH=Win64"
"* PROJECT_PATH=c:/Nextcloud/client-building"
"* WIN_GIT_PATH=C:\Program Files\Git"
"* VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC"
"* OPENSSL_ROOT_DIR=c:/OpenSSL/Win64"
"* ZLIB_PATH=c:/Nextcloud/client-building/libs/Release/zlib/Win64"
"* EXTRA_DEPLOY_PATH=c:/Nextcloud/client-building/deploy-extra/Release/Win64"
"* DLL_SUFFIX="
"* MY_REPO=c:/Nextcloud/client-building/desktop"
"* MY_BUILD_PATH=c:/Nextcloud/client-building/desktop/build"
"* MY_INSTALL_PATH=c:/Nextcloud/client-building/install/Release/Win64"
"* MY_QT_DEPLOYMENT_PATH=c:/Nextcloud/client-building/install/Release/Win64/qt-libs"
"* MY_COLLECT_PATH=c:/Nextcloud/client-building/collect/Release/Win64"
"* PATH=c:/Qt/5.12.5/msvc2017_64/bin;c:/Nextcloud/tools/cmake/bin;c:/Nextcloud/tools;C:/Program Files (x86)/NSIS;c:/Nextcloud/tools/cmake/bin;c:/Nextcloud/tools;C:/Program Files (x86)/NSIS;C:\Users\User\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\User\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\dotnet;C:\Program Files\MicroStrategy\Desktop\DataServices\180_192\64-bit\bin\server;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\Users\User\AppData\Local\Programs\Python\Python38\Scripts;C:\OpenSSL\Win64\bin;C:\Program Files\Git\cmd;C:\Qt;C:\CMake\bin;C:\zlib\bin;C:\zlib\lib;C:\zlib\include;C:\qtkeychain-master;C:\Users\User\AppData\Local\Programs\Python\Python37\Scripts;C:\Users\User\AppData\Local\Programs\Python\Python37;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Program Files\CMake\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl"
"* USE_CODE_SIGNING=1"
**"Missing environment variable: P12_KEY_PASSWORD"**
"*** Build FAILED: installer-collect Release Win64 (single-build-installer-collect.bat)"
"***** Build FAILED (build.bat)"
``

**Comment by luke5sky** [comment]
Same thing here

**Comment by rullzer** [comment]
This is to sign the binary. You'll need to get your own if you want to sign it.
