### ISSUE TITLE
which openssl archives to use?

### ISSUE THREAD

**Issue by wdehoog** [nextcloud/client-building#2]
Which openssl archives from the given link need to be used? I tried openssl-1.0.2o-x64_86-win64.zip and openssl-1.0.2o-x64_86-win64_LinkLibs.zip but they do not contain any include file.

**Comment by wdehoog** [comment]
In the install list you mention: OpenSSL: https://indy.fulgan.com/SSL/ 
but in the DLL's section you refer to C:\OpenSSL-Win64\bin

**Comment by hiiamok** [comment]
@wdehoog you need OpenSSL 1.1 for building the client, but additionally need dll's of OpenSSL 1.0 to start the client. It is mentioned in the README

> had to fetch the extra dll's from https://indy.fulgan.com/SSL/openssl-1.0.1h-x64_86-win64.zip (libeay32.dll and ssleay32.dll)

**Comment by wdehoog** [comment]
#hiiamok:

- Where does it mention one needs OpenSSL 1.1 for building and where does it mention the location it can be downloaded from?
- Where does it mention how to get cmake use the required OpenSSL include and lib?
- Why does it mention 'libcrypto-1_1-x86.dll (C:\OpenSSL-Win64\bin)' while the nightly build contains libcrypto-1_1-x64.dll?

I really appreciate nextcloud have taken time to write down a how-to but every time I try to follow one it does not work and takes a lot time to get something build.

**Comment by hiiamok** [comment]
@wdehoog 

> Where does it mention one needs OpenSSL 1.1 for building and where does it mention the location it can be downloaded from?
Take a look at this: https://github.com/nextcloud/desktop/wiki/System-requirements-for-compiling-the-desktop-client

> Where does it mention how to get cmake use the required OpenSSL include and lib?
https://github.com/nextcloud/desktop/wiki/How-to-compile-the-desktop-client
https://github.com/nextcloud/client-building/blob/master/build.bat

> Why does it mention 'libcrypto-1_1-x86.dll (C:\OpenSSL-Win64\bin)' while the nightly build contains libcrypto-1_1-x64.dll?
Well I guess the build server was set up differently than @camilasan described in this repo.

I had problems at the beginning as well (just see https://github.com/nextcloud/desktop/issues/426).
Since the Client is changing quite a lot, the way it can be build has changed as well. I guess it's quite hard for the Nextcloud team to keep the documentation up to date, but as far as I see, they are doing their best.

**Comment by wdehoog** [comment]
@hiiamok 

So the information is to be gathered from several places? I think there shoud be one place only. If possible here in this repo. This way it is less hard for the team to keep the information correct.

I took a look at https://github.com/nextcloud/desktop/wiki/System-requirements-for-compiling-the-desktop-client and it does not point to the OpenSSL to use for building. Mentioning 1.1 is not enough. They should point out exactly what to download, where to install and how to use it.

I have no doubt they do their best and I happily use the fruits of their efforts. I am only trying to help increasing their effectiveness.

**Comment by awesome-manuel** [comment]
@wdehoog I don't think it's a good idea to have build instructions in a separate repo. The build instructions should be in https://github.com/nextcloud/desktop either in the wiki or even better in the doc sections of the code. Otherwise instructions and actual requirements will always diverge.

**Comment by misch7** [comment]
Build instructions updated ;-)
