### ISSUE TITLE
How to build the shell extensions (windows)

### ISSUE THREAD

**Issue by wdehoog** [nextcloud/client-building#3]
How should the shell extensions fro windows be built? 

I opened the shell_integration\windows\OCShellExtensions.sln with Microsoft Visual Studio and 'build' it. Now I have some dll's in binary\shell_integration\windows\Release\Win32.
Is this the correct way?

**Comment by hiiamok** [comment]
@wdehoog 
Do you mean the possibility to share files from Windows Explorer? Or see their sync state in Windows Explorer? This should be integrated in the normal build.

**Comment by wdehoog** [comment]
Then it probaby is a problem of the 2.4 branch I try to build.
