### ISSUE TITLE
Zlib library not found

### ISSUE THREAD

**Issue by awesome-michael** [nextcloud/client-building#4]
When I try to build the client on Windows I get the following linking error:

` LINK : fatal error LNK1181: Eingabedatei "<path to zlib>\lib.obj" kann nicht geöffnet werden. [<path to client source>\build\src\csync\ocsync.vcxproj]`

The pathes are correct and I used the zlib you linked in the description (64 bit release). Why is it searching for 'lib.obj'? There are .lib files in the lib folder of zlib but I cant find a .obj file.

**Comment by andresantacruz** [comment]
Can you show the entire command line you are using to build with the cmake? I remember I had this same issue but it was caused by a missing slash or a missing quote in the command line, I can't remember well.

**Comment by awesome-michael** [comment]
I solved the problem. The path to zlib libraries has to point directly onto the .lib file, otherwise the linker searches for the lib.obj file. Here are the ENV VARS I used:

 ZLIB_INCLUDE_DIR (path-to-zlib-folder/include)
 ZLIB_LIBRARIES ( path-to-zlib-folder/lib/zlib.lib)
