### ISSUE TITLE
build.bat qtkeychain issue

### ISSUE THREAD

**Issue by Janl1** [nextcloud/client-building#48]
I am trying to build the nextcloud client version 3.0.3 with the stable-3.0 branch of the client-building repository.
All the dependencies are in the exact same location specified in the readme.

I appreciate you help!

```
-- Could NOT find INOTIFY (missing: INOTIFY_INCLUDE_DIR INOTIFY_LIBRARY_DIR) 
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
-- Could NOT find PdfLatex (missing: PDFLATEX_EXECUTABLE) 
-- Found OpenSSL: optimized;C:/OpenSSL/Win64/lib/VC/libcrypto64MD.lib;debug;C:/OpenSSL/Win64/lib/VC/libcrypto64MDd.lib (found suitable version "1.1.1d", minimum required is "1.1")  
-- Found ZLIB: c:/Nextcloud/client-building/libs/Release/zlib/Win64/lib/zlib.lib (found version "1.2.11") 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find GLib2 (missing: GLib2_LIBRARY GLib2_INCLUDE_DIR) 
================> LIBCLOUDPROVIDERS_LIBRARY-NOTFOUND
-- Could NOT find LIBCLOUDPROVIDERS (missing: LIBCLOUDPROVIDERS_INCLUDE_DIR LIBCLOUDPROVIDERS_LIBRARY) 
CMake Error at src/CMakeLists.txt:10 (find_package):
  By not providing "FindQt5Keychain.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Keychain", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Keychain" with
  any of the following names:

    Qt5KeychainConfig.cmake
    qt5keychain-config.cmake

  Add the installation prefix of "Qt5Keychain" to CMAKE_PREFIX_PATH or set
  "Qt5Keychain_DIR" to a directory containing one of the above files.  If
  "Qt5Keychain" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
See also "C:/Nextcloud/client-building/desktop/build/CMakeFiles/CMakeOutput.log".
"*** Build FAILED: desktop Release Win64 (single-build-desktop.bat)"
"***** Build FAILED (build.bat)"
--- END: C:\Nextcloud\client-building\task-build-log.bat - 2020-12-02 14:30:09 ---

```

The full build log is attached.
[last-build-2020-12-02-14-28-57-Release.log](https://github.com/nextcloud/client-building/files/5629576/last-build-2020-12-02-14-28-57-Release.log)

**Comment by camilasan** [comment]
This is something we changed with https://github.com/nextcloud/desktop/pull/2603 and the README here didn't get updated.

If you do what the error message says it should work:
> Add the installation prefix of "Qt5Keychain" to CMAKE_PREFIX_PATH or set
  "Qt5Keychain_DIR" to a directory containing one of the above files.

**Comment by Janl1** [comment]
Thanks for the quick response,

I am still a little bit confused what to do...
In order to add Qt5Keychain to CMAKE_PREFIX_PATH I need some folder containing bin/ include/ lib/ folders which i cannot find.
The qt5keychain.dll binary is successfully build by single-build-qtkeychain.bat and copied to C:\Qt\5.12.9\msvc2017\bin

**Comment by camilasan** [comment]
Sorry my last reply didn't make much sense :)

I need to discuss with my colleagues... but for now if you cherry-pick this commit https://github.com/nextcloud/client-building/commit/82f59b5251ee21b9d655fa26bba4e5852ced2e81 to the stable-3.0 branch you should have your problem solved.
