### ISSUE TITLE
Build error: ocsync.dll No such file or directory

### ISSUE THREAD

**Issue by mmarif4u** [nextcloud/client-building#58]
I have installed all the required libs and applications for building the Windows desktop client.

While building using `./build.bat` I get the following error:
> "* copy ocsync.dll."
cp: cannot stat 'c:/Nextcloud/client-building/install/Release/Win64/bin/Nextcloud/ocsync.dll': No such file or directory
"*** Build FAILED: installer-collect Release Win64 (single-build-installer-collect.bat)"
"***** Build FAILED (build.bat)"

Also there is no `ocsync.dll` in the collect/Release/Win64 directory, which means something is missing OR I have missed something in the process.

**Comment by er-vin** [comment]
Hm, indeed this changed a bit, looks like client-building didn't catch up. You don't have ocsync.dll, but you do have a Nextcloud_csync.dll right?

**Comment by mmarif4u** [comment]
@er-vin yes that's right, `nextcloud_csync.dll` is there. How to fix this?

Not related but thought to ask here, right now the script pull desktop from master branch, is there a way to tell it to pull from stable branch only?

**Comment by er-vin** [comment]
> @er-vin yes that's right, `nextcloud_csync.dll` is there. How to fix this?

Please test the branch adjust_to_renamed_csync from #59 and let me know how this goes.
 
> Not related but thought to ask here, right now the script pull desktop from master branch, is there a way to tell it to pull from stable branch only?

You can change TAG_DESKTOP in the config to point to something else than master.

**Comment by mmarif4u** [comment]
@er-vin hoping this should work, I believe there could be a problem with app name camel case. While the dll name is `nextcloud_csync.dll`, the current changes will produce `Nextcloud_csync.dll` by `%APP_NAME_SANITIZED%_csync.dll`, means the build will fail again. Just my thoughts.

I am going build with these changes though, but have the feeling this may fail unless `%APP_NAME_SANITIZED%` match the csync file.

Should I remove the collect folder to get the correct filename?

**Comment by er-vin** [comment]
> Should I remove the collect folder to get the correct filename?

I would say try with a clean build indeed.

**Comment by mmarif4u** [comment]
Will do that.

Just a side note, I have just compiled it from stable branch and it was built successfully, so it might be the current master branch with new changes introduced.

**Comment by er-vin** [comment]
> Will do that.
> 
> Just a side note, I have just compiled it from stable branch and it was built successfully, so it might be the current master branch with new changes introduced.

Ah yes if you do this it doesn't tell me much for the patch. ;-)

Word of caution: client-building master is for desktop master, client-building stable-3.1 is for desktop stable-3.1 and so on. Better not mix them.

**Comment by mmarif4u** [comment]
> Word of caution: client-building master is for desktop master, client-building stable-3.1 is for desktop stable-3.1 and so on. Better not mix them.

Thank you, I should have clarified that earlier.

**Comment by er-vin** [comment]
> PR #59 is still valid as desktop master with client-desktop master has the issue.

Sorry, I'm not sure I understood you properly there. Do you mean that #59 doesn't repair the issue? You can't build desktop master with the branch adjust_to_renamed_csync?

**Comment by mmarif4u** [comment]
> Sorry, I'm not sure I understood you properly there. Do you mean that #59 doesn't repair the issue? You can't build desktop master with the branch adjust_to_renamed_csync of client-building?

Sorry for the confusion. You changes are valid and works.

Have built it from master with your branch changes.

**Comment by er-vin** [comment]
OK, thanks for testing it.
