### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by gruessung** [nextcloud/client-building#7]
Is there any possibility to build NC desktop for windows / linux / mac automatically with docker?
I found admin/win/docker in nc desktop repo, but this outdated, right?

**Comment by supportreq** [comment]
getting the following error while using docker:

➜  docker git:(master) docker build . -t nextcloud-client-win32:2.5.3
Sending build context to Docker daemon  4.608kB
Step 1/14 : FROM opensuse:42.1
manifest for opensuse:42.1 not found

**Comment by misch7** [comment]
Hey @gruessung, it's not possible to build NC desktop for Windows or Mac with Docker.

**For Linux:**
Use these helper scripts to build with Docker. You'll have to modify the scripts, e.g. tweak the SCP upload:
https://github.com/nextcloud/client-building/tree/master/linux

**For Windows:**
Use the new build system, follow the step-by-step documentation:
https://github.com/nextcloud/client-building/

**For Mac:**
I'm currently upgrading the build process and will write some documentation when it's done ;)

**Comment by gruessung** [comment]
Thanks @misch7 :)
