### ISSUE TITLE
"*** Build FAILED: desktop Release Win64 (single-build-desktop.bat)"

### ISSUE THREAD

**Issue by Silva-Macaneta** [nextcloud/client-building#82]
Hi guys, I'm struggling to build the client on my win10 x64 machine. The build fails without a clear indication of what went wrong.

Here are the last line of the logs before it fails:
`
  hydrationjob.cpp
  vfs_cfapi.cpp
  mocs_compilation_Release.cpp
  Generating Code...
     Creating library C:/Nextcloud/client-building/desktop/build/src/libsync/vfs/cfapi/Release/nextcloudsync_vfs_cfapi.lib and object C:/Nextcloud/client-building/desktop/build/src/libsync/vfs/cfapi/Release/nextcloudsync_vfs_cfapi.exp
  nextcloudsync_vfs_cfapi.vcxproj -> C:\Nextcloud\client-building\desktop\build\bin\Release\nextcloudsync_vfs_cfapi.dll
  Automatic MOC for target nextcloudsync_vfs_suffix
  Building Custom Rule C:/Nextcloud/client-building/desktop/src/libsync/vfs/suffix/CMakeLists.txt
  vfs_suffix.cpp
  mocs_compilation_Release.cpp
  Generating Code...
     Creating library C:/Nextcloud/client-building/desktop/build/src/libsync/vfs/suffix/Release/nextcloudsync_vfs_suffix.lib and object C:/Nextcloud/client-building/desktop/build/src/libsync/vfs/suffix/Release/nextcloudsync_vfs_suffix.exp
  nextcloudsync_vfs_suffix.vcxproj -> C:\Nextcloud\client-building\desktop\build\bin\Release\nextcloudsync_vfs_suffix.dll
"*** Build FAILED: desktop Release Win64 (single-build-desktop.bat)"
"***** Build FAILED (build.bat)"
`
I have installed QT5 v5.12.9, OpenSSL, GnuWin32, qtkeychain along with other required dependencies highlighted by previous failed builds. 

Here are the environment variables I've added to path:
`
C:\OpenSSL\Win64\bin;
C:\Program Files (x86)\GnuWin32\bin;
C:\Program Files (x86)\GnuWin32\lib;
C:\Qt\5.12.9\msvc2017_64\bin;
C:\Qt\5.12.9\msvc2017_64\lib;
`
Environment variables:
`
CMAKE_MAKE_PROGRAM=C:\Qt\5.12.9\msvc2017_64\lib
OPENSSL_CONF=C:\OpenSSL\Win64\bin\openssl.cfg
QT_INSTALL_PREFIX=C:\Qt\5.12.9
QT_PATH=C:\Qt\5.12.9
QTDIR=C:\Qt\5.12.9
`
Any help or clarification would be much appreciated.

**Comment by FlexW** [comment]
The error probably happens a lot earlier. Try to read the complete output and look for an error. But please keep in mind that this is not a support forum. You can get support from the community at help.nextcloud.com
