### ISSUE TITLE
stable-3.3 build error with  code 

### ISSUE THREAD

**Issue by Allenscript** [nextcloud/client-building#84]
it like this ,
`C:\Nextcloud\client-building\desktop\src\libsync\theme.cpp(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失 [C:\Nextcloud\client-building\desktop\build\src\libsync\nextcloudsync.vcxproj]
C:\Nextcloud\client-building\desktop\src\libsync\theme.cpp(108,58): error C2001: 常量中有换行符 [C:\Nextcloud\client-building\desktop\build\src\libsync\nextcloudsync.vcxproj]
C:\Nextcloud\client-building\desktop\src\libsync\theme.cpp(109,9): error C2143: 语法错误: 缺少“)”(在“break”的前面) [C:\Nextcloud\client-building\desktop\build\src\libsync\nextcloudsync.vcxproj]
C:\Nextcloud\client-building\desktop\src\libsync\theme.cpp(109,9): error C2143: 语法错误: 缺少“;”(在“break”的前面) [C:\Nextcloud\client-building\desktop\build\src\libsync\nextcloudsync.vcxproj]
  clientsideencryption.cpp
C:\Nextcloud\client-building\desktop\src\libsync\clientsideencryption.cpp(298,42): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据 [C:\Nextcloud\client-building\desktop\build\src\libsync\nextcloudsync.vcxproj]
C:\Nextcloud\client-building\desktop\src\libsync\clientsideencryption.cpp(756,32): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据 [C:\Nextcloud\client-building\desktop\build\src\libsync\nextcloudsync.vcxproj]
C:\Nextcloud\client-building\desktop\src\libsync\clientsideencryption.cpp(807,32): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据 [C:\Nextcloud\client-building\desktop\build\src\libsync\nextcloudsync.vcxproj]
`
my system  info:
os: win7
vscode 2019
qt 5.12.11

**Comment by FlexW** [comment]
Sorry, I'm not able to understand Chinese (or whatever that language is).  There were some issues in stable-3.3 which should now be resolved.
