### ISSUE TITLE
Error copy my_app_name_csync.dll

### ISSUE THREAD

**Issue by afprobst** [nextcloud/client-building#85]
Hello Michael! A few weeks ago I successfully generated my version by following your scripts and changing app_name to my name. Now the compilation gave an error and asked to update QT to version 5.15.2 and after that the dlls were not generated with my name. And now it stops with this cp error: cannot stat 'c:/Nextcloud/client-building/install/Release/Win64/bin/my_app_name_csync.dll': No such file or directory
Help!!!

**Comment by FlexW** [comment]
You probably need to update your Qt version. Please read the compilation output carefully. The real error probably happens a lot earlier. It should give you an indication of what's wrong. Please keep in mind that this is not a support forum. You can get help from the community at help.nextcloud.com.
