### ISSUE TITLE
Use /d "description" to have better file name in UAC within Windows installer

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/client-building#98]
![image](https://user-images.githubusercontent.com/5836855/146325036-ccceb78f-d56a-4c7d-8f4b-72822aa8722e.png)

https://docs.microsoft.com/en-us/windows/win32/seccrypto/signtool#sign-command-options
/d option

Needed to be changed in: https://github.com/nextcloud/client-building/blob/master/single-build-installer-msi.bat#L114

**Comment by Rello** [comment]
fixed with https://github.com/nextcloud/client-building/pull/131 & 3.15.1
